version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce
    hostname: 'fortport.testlab.local'
    ports:
      - "9000:9000"
    #   - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - 95-network
        
  plc:
    image: liveforensics/plc:1.0.0
    container_name: plc
    networks:
      - 95-network
    ports:
      - "30022:22"
      - "8080:8080"
                    
networks:
  95-network:
      driver: bridge
  90-network:

volumes:
  portainer_data: