version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce
    hostname: 'fortport.testlab.local'
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - testlab-network
        
  plc:
    image: liveforensics/plc:1.0.0
    container_name: plc
    networks:
      95-network:
        ipv4_address: 192.168.95.200
    ports:
      - "30022:22"
      - "8080:8080"
                    
networks:
  95-network:
    driver: macvlan
    driver_opts:
      parent: ens224
    ipam:
      driver: default
      config:
        - subnet: 192.168.95.0/24
          gateway: 192.168.95.1
  90-network:
    driver: macvlan
    driver_opts:
      parent: ens256
    ipam:
      driver: default
      config:
        - subnet: 192.168.90.0/24
          gateway: 192.168.95.100
  testlab-network:
    driver: bridge

volumes:
  portainer_data: