FROM liveforensics/linuxstarter:1.0.1

COPY inputs.conf /opt/splunkforwarder/etc/system/local/inputs.conf
COPY outputs.conf /opt/splunkforwarder/etc/system/local/outputs.conf


RUN yum -y install gcc sshpass

    
    