pipeline {
    agent {
        node {
            label 'WinDockerBuildAgent'
        }
    }
    stages {
        stage('Simple Test') {
            steps {
                script {
                    try {
                        def status = bat(returnStatus: true, script: 'docker ps')
                        if(status != 0) {
                            error('DOCKER PULL FAILED') 
                        }
                    }
                    catch (ex) {
                        echo "Caught: ${ex}"
                        throw ex
                    }
                    
                }                          
            }
        }
    }
}
