version: '2'

services:
    plc:
        image: liveforensics/plc:1.0.0
        container_name: plc
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - 95-network
        ports:
            - "30022:22"
            - "8080:8080"
                    
networks:
    95-network:
        driver: bridge
    90-network:
        