version: '3.2'

services:
  orchestrator:
    image: jenkins/jenkins:lts
    networks:
      - testlabnet
    ports:
        - "8080:8080"
        - "50000:50000"
    deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints: [node.role == manager]

  buildbox:
    image: liveforensics/buildbox:2004
    networks:
      - testlabnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == windows]
      resources:
        limits:
          cpus: '0.50'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 2G

networks:
  testlabnet:
    driver: overlay
    attachable: true