version: '3.2'

services:
  orchestrator:
    image: jenkins/jenkins:latest
    hostname: 'jenkins.testlab.local'
    networks:
      testlab-network:
        ipv4_address: 10.12.1.2
    # ports:
    #     - "8080:8080"
    #     - "50000:50000"
    volumes:
      - /home/sysadmin/docker-shared/user-volumes/orchestrator/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.http.routers.orchestrator.rule=Host(`jenkins.testlab.local`)"
        - "traefik.http.routers.orchestrator.rule=Host(`jenkins.mark.net`)"
        - "traefik.http.services.orchestrator.loadbalancer.server.port=8080"
        - "traefik.http.routers.orchestrator.entrypoints=http"
        - "traefik.tcp.routers.orchestrator.entrypoints=orchestrator"
        # - "traefik.tcp.routers.orchestrator.rule=Host(`jenkins.testlab.local`)"
        - "traefik.tcp.services.orchestrator.loadbalancer.server.port=50000"
        - "traefik.tcp.routers.orchestrator.rule=HostSNI(`jenkins.testlab.local`)"

  buildtoolsppc:
    image: liveforensics/buildbox:2004-powerpc
    hostname: 'buildtoolsppc.testlab.local'
    networks:
      - testlab-network
    environment:
    # notice the secret sauce here, you have to prefix container names with tasks. in order for the internal dns to resolve to the actual container!
      - JENKINS_URL=http://tasks.orchestrator:8080
      - JENKINS_SECRET=337c310420cb94b36afe963dbeba20fabf8457b446831632ede1705ffe6968f2
      - JENKINS_AGENT_NAME=ppc
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == windows]
      resources:
        limits:
          cpus: '0.50'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 2G

  buildtools2019:
    image: liveforensics/buildbox:2004-buildtools2019
    hostname: 'buildtools2019.testlab.local'
    networks:
      - testlab-network
    environment:
      - JENKINS_URL=http://tasks.orchestrator:8080
      - JENKINS_SECRET=99de84f5fb9517dc5ec0d2a985b193647ff18c244d54db8adedcf4f462cc6d91 
      - JENKINS_AGENT_NAME=buildtools2019
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == windows]
      resources:
        limits:
          cpus: '0.50'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 2G

  linuxdockeragent:
    image: liveforensics/linuxdockerslave:latest
    hostname: linuxdockerslave.testlab.local
    networks:
      - testlab-network
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]    

        
  # buildbox2:
  #   image: liveforensics/buildboxgcc:1.0.0-jenkins
  #   networks:
  #     - testlabnet
  #   ports:
  #     - "30022:22" 
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     placement:
  #       constraints: [node.platform.os == linux]

  # sdk71:
  #   image: liveforensics/buildbox:2004-sdk7.1-jenkins
  #   networks:
  #     - testlabnet
  #   ports:
  #     - "20022:22" 
  #   environment:
  #     - JENKINS_URL=http://dockerhost01.testlab.local:8080/computer/sdk7/slave-agent.jnlp
  #     - JENKINS_SECRET=2858399af1e04a1ebe792aa60f2c5dce36e67a2f723a944fce95a17725d55c9e
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     placement:
  #       constraints: [node.platform.os == windows]
  #     resources:
  #       limits:
  #         cpus: '0.50'
  #         memory: 2G
  #       reservations:
  #         cpus: '0.25'
  #         memory: 2G
          

  nexus:
    image: sonatype/nexus3
    hostname: 'nexus.testlab.local'
    networks:
      - testlab-network
    # ports:
    #   - "8081:8081"
    volumes:
      - /home/sysadmin/docker-shared/user-volumes/nexus3:/nexus-data
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.http.routers.nexus.rule=Host(`nexus.testlab.local`)"
        - "traefik.http.services.nexus-service.loadbalancer.server.port=8081"
        - "traefik.http.routers.nexus.entrypoints=http"

# networks:
#   testlabnet:
#     driver: overlay
#     attachable: true

networks:
  testlab-network:
    external: true
