version: '3.2'

services:
  orchestrator:
    image: jenkins/jenkins:latest
    networks:
      - testlabnet
    ports:
        - "8080:8080"
        - "50000:50000"
    volumes:
      - /home/sysadmin/docker-shared/user-volumes/orchestrator/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints: [node.role == manager]

  buildbox:
    image: liveforensics/buildbox:2004-powerpc
    networks:
      - testlabnet
    environment:
      - JENKINS_URL=http://dockerhost01.testlab.local:8080
      - JENKINS_SECRET=337c310420cb94b36afe963dbeba20fabf8457b446831632ede1705ffe6968f2
      - JENKINS_AGENT_NAME=ppc
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == windows]
      resources:
        limits:
          cpus: '0.50'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 2G

  # buildbox3:
  #   image: liveforensics/buildbox:2004-full-jenkins
  #   networks:
  #     - testlabnet
  #   environment:
  #     - JENKINS_URL=http://dockerhost01.testlab.local:8080/computer/Windows%20dotnet/slave-agent.jnlp
  #     - JENKINS_SECRET=a295b8a618dc7b5b525395ffeedea6a58b79cb3ae5e5382c2b6bed2f6bf6bef3
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     placement:
  #       constraints: [node.platform.os == windows]
  #     resources:
  #       limits:
  #         cpus: '0.50'
  #         memory: 2G
  #       reservations:
  #         cpus: '0.25'
  #         memory: 2G
        
  # buildbox2:
  #   image: liveforensics/buildboxgcc:1.0.0-jenkins
  #   networks:
  #     - testlabnet
  #   ports:
  #     - "30022:22" 
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     placement:
  #       constraints: [node.platform.os == linux]

  # sdk71:
  #   image: liveforensics/buildbox:2004-sdk7.1-jenkins
  #   networks:
  #     - testlabnet
  #   ports:
  #     - "20022:22" 
  #   environment:
  #     - JENKINS_URL=http://dockerhost01.testlab.local:8080/computer/sdk7/slave-agent.jnlp
  #     - JENKINS_SECRET=2858399af1e04a1ebe792aa60f2c5dce36e67a2f723a944fce95a17725d55c9e
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     placement:
  #       constraints: [node.platform.os == windows]
  #     resources:
  #       limits:
  #         cpus: '0.50'
  #         memory: 2G
  #       reservations:
  #         cpus: '0.25'
  #         memory: 2G
          
  # agenttest:
  #   image: liveforensics/jenkinsagent:2004
  #   networks:
  #     - testlabnet
  #   environment:
  #     - JENKINS_URL=http://dockerhost01.testlab.local:8080
  #     - JENKINS_SECRET=672968099a0a56df6965c939f385bd2541a50846ca1a1c1f970f1135e9bdb312
  #     - JENKINS_AGENT_NAME=TestMe
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     placement:
  #       constraints: [node.platform.os == windows]
  #     resources:
  #       limits:
  #         cpus: '0.50'
  #         memory: 1G
  #       reservations:
  #         cpus: '0.25'
  #         memory: 1G    

  nexus:
    image: sonatype/nexus3
    networks:
      - testlabnet
    ports:
      - "8081:8081"
    volumes:
      - /home/sysadmin/docker-shared/user-volumes/nexus3:/nexus-data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]

networks:
  testlabnet:
    driver: overlay
    attachable: true


#  