version: '3.2'

services:
  orchestrator:
    image: jenkins/jenkins:lts
    # networks:
    #   - testlabnet
    ports:
        - "8080:8080"
        - "50000:50000"
    deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints: [node.role == manager]

