version: '3.2'

services:
  orchestrator:
    image: jenkins/jenkins:latest
    hostname: 'jenkins.testlab.local'
    networks:
      - traefik-public
    # labels:
    #   - "traefik.http.routers.whoami.rule=Host(`whoami.testlab.local`)"
    # ports:
    #   - "8082:8080"
    #   - "50000:50000"
    volumes:
      - jenkins-home:/var/jenkins_home
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.http.routers.orchestrator.rule=Host(`jenkins.testlab.local`)"
        - "traefik.http.services.orchestrator-service.loadbalancer.server.port=8080"

  whoami2:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    hostname: 'whoami2.testlab.local'
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 3
      labels:
        - "traefik.http.routers.whoami2.rule=Host(`whoami2.testlab.local`)"
        - "traefik.http.services.whoami2-service.loadbalancer.server.port=80"
                  

  # nexus:
  #   image: sonatype/nexus3
  #   # networks:
  #   #   - traefik-public
  #   # labels:
  #   #   - "traefik.http.routers.nexus.rule=Host(`nexus.testlab.local`)"
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - nexus-home:/nexus-data
  #   deploy:
  #     mode: replicated
  #     replicas: 3
  #     placement:
  #       constraints: [node.platform.os == linux]
  #   labels:
  #     - traefik.http.routers.nexus.rule=Host(`nexus.testlab.local`)
  #     # - traefik.http.routers.nexus-public-http.entrypoints=http
  #     - traefik.http.services.nexus-service.loadbalancer.server.port=8081

volumes:
  # Create a volume to store the certificates, there is a constraint to make sure
  # Traefik is always deployed to the same Docker node with the same volume containing
  # the HTTPS certificates
  jenkins-home:
  nexus-home:

networks:
  traefik-public:
    external: true


