version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:latest
    hostname: 'traefik.testlab.local'
    networks:
      - testlab-network
    deploy:
      mode: replicated
      replicas: 1

    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - --api.insecure=true 
      - --providers.docker 
      - --providers.docker.swarmMode=true
      - --entrypoints.web.address=:80
      - --entrypoints.orchestrator.address=:50001
    ports:
    # The HTTP port
      - "80:80"
    # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      - "50001:50000"
    volumes:
    # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock


  # whoami:
  #   # A container that exposes an API to show its IP address
  #   image: traefik/whoami
  #   hostname: 'whoami.testlab.local'
  #   networks:
  #     - testlab-network
  #   deploy:
  #     labels:
  #       - "traefik.http.routers.whoami.rule=Host(`whoami.testlab.local`)"      
  #       - "traefik.http.services.whoami-service.loadbalancer.server.port=80"

  #       # iwr http://127.0.0.1 -Headers @{'Host' = 'whoami.docker.localhost'}


networks:
  testlab-network:
    external: true

