version: '2'

services:
    linuxstarter:
        image: liveforensics/linuxstarter:1.0.1
        container_name: linuxstarter
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - local-network
                    
networks:
    local-network:
        driver: bridge
        
