version: '2.2'

services:  

  BuildSlave:
    image: liveforensics/splunkins:2.0.0
    container_name: splunkins
    hostname: splunkins
    networks:
      - jenkins-network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - c:\docker\persistroot:c:\Persist    
      - c:\docker\volumes\buildtools:c:\BuildTools
      - c:\docker\volumes\Microsoft.NET:c:\Windows\Microsoft.NET
      - c:\docker\volumes\Windows Kits:c:\Program Files (x86)\Windows Kits
      - c:\docker\volumes\Microsoft SDKs:c:\Program Files (x86)\Microsoft SDKs
      - c:\docker\volumes\Microsoft Visual Studio:c:\Program Files (x86)\Microsoft Visual Studio
      - c:\docker\volumes\Microsoft Visual Studio 14.0:c:\Program Files (x86)\Microsoft Visual Studio 14.0
      - c:\docker\volumes\Reference Assemblies:c:\Program Files (x86)\Reference Assemblies
    environment:
      - JENKINS_URL=http://dockerdude.ukwest.cloudapp.azure.com:10008/computer/DockerOne/slave-agent.jnlp
      - JENKINS_SECRET=00a9c8b49dbcb471d86d33e9107ddcfdeaeb24f56f8661256d2e1f5e78b7c632 
      - SPLUNK_HOST=dockerdude.ukwest.cloudapp.azure.com
      - SPLUNK_PORT=10009


    mem_limit: 4G
   
  
networks:
    jenkins-network:
        driver: nat


