version: '2.2'

services:  

  BuildSlave:
    image: liveforensics/buildslave:1.0.7
    container_name: buildslave
    hostname: buildslave
    networks:
      - jenkins-network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - c:\docker\persistroot:c:\Persist    
      - c:\docker\volumes\buildtools:c:\BuildTools
      - c:\docker\volumes\Microsoft.NET:c:\Windows\Microsoft.NET
      - c:\docker\volumes\Windows Kits:c:\Program Files (x86)\Windows Kits
      - c:\docker\volumes\Microsoft SDKs:c:\Program Files (x86)\Microsoft SDKs
      - c:\docker\volumes\Microsoft Visual Studio:c:\Program Files (x86)\Microsoft Visual Studio
      - c:\docker\volumes\Microsoft Visual Studio 14.0:c:\Program Files (x86)\Microsoft Visual Studio 14.0
      

    mem_limit: 2G
   
    
  # JenkinsWindowsSlaveEnt2:
  #   image: liveforensics/jenkinswindowsslave:ent-1.0.0
  #   container_name: JenkinsSlaveEnt2
  #   networks:
  #     - jenkins-network
  #   environment:
  #     - JENKINS_URL=http://dockerdude.ukwest.cloudapp.azure.com:10008/computer/DockerTwo/slave-agent.jnlp
  #     - JENKINS_SECRET=e2d90db5820bae44edc0d515914e90eade8f129962a8d330d4ae9071cab04a3f
  #   mem_limit: 2G

  # docker run -d -p 9000:9000 --name portainer --restart always -v \\.\pipe\docker_engine:\\.\pipe\docker_engine -v C:\docker\Portainer:C:\data portainer/portainer
  # 
  # portainer:
  #   image: portainer/portainer
  #   container_name: portainer
  #   networks:
  #       - jenkins-network
  #   ports:
  #       - "9000:9000"
  #   volumes:
  #       - "\\\\.\\pipe\\docker_engine:\\\\.\\pipe\\docker_engine"
  #       - c:\docker\portainer:c:\data

networks:
    jenkins-network:
        driver: nat


