version: '2.2'

services:  

  WindowsSlave:
    image: liveforensics/windowsslave:1.0.0
    container_name: windowsslave
    hostname: windowsslave
    networks:
      - jenkins-network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - c:\docker\persistroot:c:\Persist    
      - E:\Visual Studio Layout\BuildTools:c:\vs_BuildTools

    mem_limit: 4G
   
  
networks:
    jenkins-network:
        driver: nat


