version: '2.1'

services:
    
  # docker run -d -p 9000:9000 --name portainer --restart always -v \\.\pipe\docker_engine:\\.\pipe\docker_engine -v C:\docker\Portainer:C:\data portainer/portainer
  
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    # networks:
    #     - jenkins-network
    ports:
        - "9000:9000"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

# networks:
#     jenkins-network:
#         driver: nat


volumes:
  portainer_data:
