version: '3.0'

services:
  buildboxsdk71:
    image: liveforensics/buildbox:1909-sdk7.1-jenkins
    container_name: buildboxsdk71
    build:
      context: .
      dockerfile: Dockerfile-1909-3
    ports:
      - "22:22"