version: '3.0'

services:
  buildboxsdk71:
    image: liveforensics/buildbox:2004-sdk7.1-jenkins
    container_name: buildboxsdk71
    build:
      context: .
      dockerfile: Dockerfile-2004-3
    ports:
      - "22:22"