version: '3.0'

services:
    buildboxgcc:
        image: liveforensics/inbound-agent:linux-1.0.1
        container_name: buildboxgcc
        build:
            context: .
            dockerfile: Dockerfile
