version: '3'

services:  

  WindowsSlave:
    image: liveforensics/jenkinsagent:1909
    container_name: jenkinsagent
    hostname: jenkinsagent
    networks:
      - jenkins-network
    build:
      context: .
      dockerfile: Dockerfile-1909
    
  
  WindowsSlave2:
    image: liveforensics/jenkinsagent:2004
    container_name: jenkinsagent2
    hostname: jenkinsagent2
    networks:
      - jenkins-network
    build:
      context: .
      dockerfile: Dockerfile-2004
    
  
networks:
    jenkins-network:
        driver: nat


