pipeline {
    agent {
        node {
            label 'windocker'
        }
    }
    stages {
        stage('Setup') {
            steps {
                powershell '''
                    Write-Output 'Cleaning Up Folders and Copying Files.....'
                    remove-item -recurse -force Linux
                    remove-item -recurse -force Swarm
                    remove-item -recurse -force Windows
                    remove-item -recurse -force BuildRoot -ErrorAction SilentlyContinue
                    New-Item -Type Directory 'BuildRoot'      
                    Copy-Item -Path Containers/powerpc/* -Destination BuildRoot -Recurse -Force              
                '''
            }
        }
        stage('Stage 1') {
            steps {                
                dir('BuildRoot') {
                    script {
                        try {
                            def status = bat(returnStatus: true, script: 'docker pull liveforensics/buildbox:2004-jenkinsagent')
                            if(status != 0) {
                                error('DOCKER PULL FAILED') 
                            }
                            status = bat(returnStatus: true, script: 'docker-compose build')
                            if(status != 0) {
                                error('DOCKER COMPOSE FAILED') 
                            }
                        }
                        catch (ex) {
                            echo "Caught: ${ex}"
                            throw ex
                        }                        
                    }  
                }                                
            }
        }
    }
    post { 
        always { 
            echo 'cleaning up the workspace'
            cleanWs()
        }
    }
}
