version: '2.1'

services:  

  JenkinsWindowsSlaveEnt:
    image: liveforensics/jenkinswindowsslave:1903-f
    container_name: JenkinsSlaveEnt
    networks:
      - jenkins-network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - c:\docker\persistroot:c:\Persist      
      # - c:\docker\buildtools:c:\BuildTools
      # - 'c:\docker\kits:c:\Program Files (x86)\Windows Kits'
    mem_limit: 2G
   
    
  # JenkinsWindowsSlaveEnt2:
  #   image: liveforensics/jenkinswindowsslave:ent-1.0.0
  #   container_name: JenkinsSlaveEnt2
  #   networks:
  #     - jenkins-network
  #   environment:
  #     - JENKINS_URL=http://dockerdude.ukwest.cloudapp.azure.com:10008/computer/DockerTwo/slave-agent.jnlp
  #     - JENKINS_SECRET=e2d90db5820bae44edc0d515914e90eade8f129962a8d330d4ae9071cab04a3f
  #   mem_limit: 2G

  # JenkinsWindowsSlaveEnt3:
  #   image: liveforensics/jenkinswindowsslave:1903
  #   container_name: JenkinsSlaveEnt3
  #   networks:
  #     - jenkins-network
  #   environment:
  #     - JENKINS_URL=http://dockerdude.ukwest.cloudapp.azure.com:10008/computer/DockerThree/slave-agent.jnlp
  #     - JENKINS_SECRET=dd0907cf11f37b0a4e294e5cd7e86adf4e1b4767b9ea8b85990fba8f4c261bd8
  #   mem_limit: 2G

  # docker run -d -p 9000:9000 --name portainer --restart always -v \\.\pipe\docker_engine:\\.\pipe\docker_engine -v C:\docker\Portainer:C:\data portainer/portainer
  # 
  # portainer:
  #   image: portainer/portainer
  #   container_name: portainer
  #   networks:
  #       - jenkins-network
  #   ports:
  #       - "9000:9000"
  #   volumes:
  #       - "\\\\.\\pipe\\docker_engine:\\\\.\\pipe\\docker_engine"
  #       - c:\docker\portainer:c:\data

networks:
    jenkins-network:
        driver: nat


