pipeline {
    agent {
        node {
            label 'WinBuilder'
        }
    }
    stages {
        stage('Preparation') {
            steps {
                echo 'do some prep'
                powershell 'remove-item -recurse -force Linux'
                // git 'https://github.com/microsoft/VCSamples.git'
                dir('Windows/openjdk') {
                    powershell 'ls'
                    bat 'docker pull mcr.microsoft.com/windows/servercore:2004'
                    bat 'docker-compose build'
                    bat 'docker push liveforensics/buildbox:2004-jenkinsagent'
                }
                
                
            }
        }
        stage('Builder') {
            steps {
                echo 'do some build magic'
                // dir('VC2015Samples\\scribble') {                    
                //     script {                    
                //         bat 'call C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat && msbuild.exe scribble.sln /p:Configuration=Debug /p:Platform=x64' 
                //     }
                // }
                
                // bat 'call C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat'
                

                // powershell 'msbuild --version'
            
            }
        }
    }
}