version: '2'

services:
    ansibleslave:
        image: liveforensics/ansibleslave:latest
        container_name: ansibleslave
        hostname: ansibleslave
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - local-network
                    
networks:
    local-network:
        driver: bridge
        
