version: '2.1'

services:
  Jenkins2:
    image: jenkins/jenkins:lts
    container_name: JenkinsMaster2
    volumes:
      - c:\temp\Jenkins_home2:/var/jenkins_home
    # networks:
    #   app_net:
    #     ipv4_address: 192.168.0.109
    ports:
      - "8081:8080"
      - "50001:50000"

volumes:
  jenkins_home:

# networks:
#   app_net:
#     ipam:
#       driver: default
#       config:
#         - subnet: "192.168.0.0/24"