pipeline {
    agent {
        node {
            label 'windocker'
        }
    }
    stages {
        stage('Setup') {
            steps {
                powershell '''
                    Write-Output 'Cleaning Up Folders and Copying Files.....'
                    remove-item -recurse -force Linux
                    remove-item -recurse -force Swarm
                    remove-item -recurse -force Windows
                    remove-item -recurse -force BuildRoot -ErrorAction SilentlyContinue
                    New-Item -Type Directory 'BuildRoot'      
                    Copy-Item -Path Containers/buildtools2019/step1/* -Destination BuildRoot -Recurse -Force              
                '''
                // echo 'cleaning up folders'
                // powershell ''
                // powershell 'remove-item -recurse -force Swarm'
                // powershell 'remove-item -recurse -force BuildRoot'
                // bat 'mkdir BuildRoot'
                // powershell ''
            }
        }
        stage('Stage 1') {
            steps {                
                dir('BuildRoot') {
                    script {
                        try {
                            def status = bat(returnStatus: true, script: 'docker pull liveforensics/buildbox:2004-powerpc')
                            if(status != 0) {
                                error('DOCKER PULL FAILED') 
                            }
                            status = bat(returnStatus: true, script: 'docker-compose build')
                            if(status != 0) {
                                error('DOCKER COMPOSE FAILED') 
                            }
                            status = bat(returnStatus: true, script: 'docker run --name step1 -v "C:\\Visual Studio Layouts\\Build Tools:c:\\vs" temp/buildbox:2004-buildtools2019-step1')
                            if(status != 0) {
                                error('DOCKER RUN FAILED') 
                            }
                            status = bat(returnStatus: true, script: 'docker commit step1 temp/step1')
                            if(status != 0) {
                                error('DOCKER COMMIT FAILED') 
                            }
                            // status = bat(returnStatus: true, script: 'docker rm step1')
                            // if(status != 0) {
                            //     error('DOCKER REMOVE FAILED') 
                            // }
                            // status = bat(returnStatus: true, script: 'docker rmi temp/buildbox:2004-buildtools2019-step1 temp/step1')
                            // if(status != 0) {
                            //     error('DOCKER REMOVE IMAGE FAILED') 
                            // }
                        }
                        catch (ex) {
                            echo "Caught: ${ex}"
                            throw ex
                        }
                        
                    }  
                    // powershell 'ls'
                    // bat 'docker pull liveforensics/buildbox:2004-powerpc'
                    // bat 'docker-compose build'
                    // bat 'docker run temp/buildbox:2004-buildtools2019-step1'
                }                                
            }
        }
        stage('Stage 2') {
            steps {
                powershell '''
                    Write-Output 'Copying files for step 2.....'
                    Remove-Item BuildRoot/*  -Recurse -Force
                    Copy-Item -Path Containers/buildtools2019/step2/* -Destination BuildRoot -Recurse -Force              
                '''

                
            
            }
        }
        stage('Stage 3') {
            steps {
                dir('BuildRoot') {
                    script {
                        try {
                            def status = bat(returnStatus: true, script: 'docker-compose build')
                            if(status != 0) {
                                error('DOCKER COMPOSE FAILED') 
                            }      
                            status = bat(returnStatus: true, script: 'docker login')
                            if(status != 0) {
                                error('DOCKER LOGIN FAILED') 
                            }  
                            status = bat(returnStatus: true, script: 'docker push liveforensics/buildbox:2004-buildtools2019')
                            if(status != 0) {
                                error('DOCKER PUSH FAILED') 
                            }                      
                        }
                        catch (ex) {
                            echo "Caught: ${ex}"
                            throw ex
                        }
                        
                    }  
                }

                
            
            }
        }
        stage('Cleanup') {
            steps {                
                dir('BuildRoot') {
                    script {
                        try {
                            def status = bat(returnStatus: true, script: 'docker rm step1')
                            if(status != 0) {
                                error('DOCKER REMOVE FAILED') 
                            }
                            status = bat(returnStatus: true, script: 'docker rmi temp/buildbox:2004-buildtools2019-step1 temp/step1')
                            if(status != 0) {
                                error('DOCKER REMOVE IMAGE FAILED') 
                            }
                        }
                        catch (ex) {
                            echo "Caught: ${ex}"
                            throw ex
                        }
                        
                    }  
                    // powershell 'ls'
                    // bat 'docker pull liveforensics/buildbox:2004-powerpc'
                    // bat 'docker-compose build'
                    // bat 'docker run temp/buildbox:2004-buildtools2019-step1'
                }                                
            }
        }
    }
    post { 
        always { 
            echo 'cleaning up the mess - hehe'
            cleanWs()
        }
    }
}
