pipeline {
    agent {
        node {
            label 'windocker'
        }
    }
    stages {
        stage('Setup') {
            steps {
                powershell '''
                    Write-Output 'Cleaning Up Folders and Copying Files...'
                    remove-item -recurse -force Linux
                    remove-item -recurse -force Swarm
                    remove-item -recurse -force Windows
                    remove-item -recurse -force BuildRoot -ErrorAction SilentlyContinue
                    New-Item -Type Directory 'BuildRoot'      
                    Copy-Item -Path Containers/buildtools2019/step1/* -Destination BuildRoot -Recurse -Force              
                '''
                // echo 'cleaning up folders'
                // powershell ''
                // powershell 'remove-item -recurse -force Swarm'
                // powershell 'remove-item -recurse -force BuildRoot'
                // bat 'mkdir BuildRoot'
                // powershell ''
            }
        }
        stage('Preparation') {
            steps {                
                dir('BuildRoot') {
                    powershell 'ls'
                    bat 'docker pull liveforensics/buildbox:2004-powerpc'
                    bat 'docker-compose build'
                    bat 'docker run temp/buildbox:2004-buildtools2019-step1'
                }                                
            }
        }
        // stage('Builder') {
        //     steps {
        //         echo 'do some build magic'
        //         // dir('VC2015Samples\\scribble') {                    
        //         //     script {                    
        //         //         bat 'call C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat && msbuild.exe scribble.sln /p:Configuration=Debug /p:Platform=x64' 
        //         //     }
        //         // }
                
        //         // bat 'call C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat'
                

        //         // powershell 'msbuild --version'
            
        //     }
        // }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}