version: '2'

services:
    terraformslave:
        image: liveforensics/terraformslave:12.17
        container_name: terraformslave
        hostname: terraformslave
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - local-network
                    
networks:
    local-network:
        driver: bridge
        
